// Definindo o enum para as categorias.
export enum Categoria {
  Aneis = "Anéis",
  Brincos = "Brincos",
  Colares = "Colares",
  Conjuntos = "Conjuntos",
  Pulseiras = "Pulseiras",
  PulseirasMasc = "Pulseiras Masculinas",
  ColarMasc = "Colares Masculinos",
}

// Definindo a interface para os produtos
interface Produto {
  nome: string;
  descricao: string;
  foto: string;
  preco: number;
  esgotado: boolean;
  categoria: Categoria;
}

// Definindo a estrutura das categorias e produtos
export const categories = [
  {
    name: Categoria.Aneis,
    foto: "DESTAQUE-ANEL.png",
    produtos: [
      {
        id: 20,
        nome: "Anel Rabo de Baleia com Coração de Zircônia Regulável",
        descricao: "regulável",
        esgotado: false,
        preco: 60,
        foto: "Anel de Prata 925 Rabo de Baleia com Coração de Zircônia Regulável.webp",
      },
      {
        id: 21,
        nome: "Anel Coração Duplo Regulável",
        descricao: "regulável",
        esgotado: false,
        preco: 50,
        foto: "Anel de Prata 925 Coração Duplo Regulável.webp",
      },
      {
        id: 22,
        nome: "Anel Ondas",
        descricao: "Tam 19",
        esgotado: false,
        preco: 50,
        foto: "Anel de Prata 925 Ondas.webp",
      },
      {
        id: 23,
        nome: "Anel Zig Zag Cravejado",
        descricao: "Tam 17",
        esgotado: false,
        preco: 60,
        foto: "Anel de Prata 925 Zig Zag Cravejado.webp",
      },
      {
        id: 24,
        nome: "Anel Cravejado Regulável Estrela e Lua",
        descricao: "regulável",
        esgotado: false,
        preco: 60,
        foto: "Anel de Prata 925 Cravejado Regulável Estrela e Lua.webp",
      },
      {
        id: 25,
        nome: "Anel Fios Minimalistas Regulável",
        descricao: "regulável",
        esgotado: false,
        preco: 50,
        foto: "Anel de Prata 925 Fios Minimalistas Regulável.webp",
      },

      {
        nome: "Anel Coração Verde",
        descricao: "TAM 16",
        esgotado: false,
        preco: 55,
        categoria: Categoria.Aneis,
        foto: "anel-coracao-verde.jpeg",
      },
      {
        nome: "Anel Corações Cravejados",
        descricao: "TAM 23",
        esgotado: false,
        preco: 60,
        categoria: Categoria.Aneis,
        foto: "anel-coracoes-pedrinhas.jpeg",
      },
      {
        nome: "Anel Meia Aliança",
        descricao: "TAM 20",
        esgotado: false,
        preco: 60,
        categoria: Categoria.Aneis,
        foto: "anel-cravejado.jpeg",
      },
      {
        nome: "Anel Amor Infinito",
        descricao: "Regulável",
        esgotado: false,
        preco: 50,
        categoria: Categoria.Aneis,
        foto: "anel-infinito-coracao.jpeg",
      },
      {
        nome: "Anel Zircônia Quadrangular",
        descricao: "TAM 18",
        esgotado: false,
        preco: 60,
        categoria: Categoria.Aneis,
        foto: "anel-pedra-quadrada.jpeg",
      },
      {
        nome: "Anel Triângulos",
        descricao: "Regulável",
        esgotado: false,
        preco: 50,
        categoria: Categoria.Aneis,
        foto: "anel-reg-triangulos.jpeg",
      },
      {
        nome: "Anel Trançado",
        descricao: "TAM 20, 17",
        esgotado: false,
        preco: 55,
        categoria: Categoria.Aneis,
        foto: "anel-trancado.jpeg",
      },
    ],
  },
  {
    name: Categoria.Brincos,
    foto: "DESTAQUE-BRINCO.png",
    produtos: [
      {
        id: 16,
        nome: "Brinco Coração Vazado Com Corações Lisos",
        descricao: "",
        esgotado: false,
        preco: 50,
        foto: "Brinco de Prata 925 Coração Vazado Com Corações Lisos.webp",
      },
      {
        id: 18,
        nome: "Brinco Ear Cuff 3 Corações",
        descricao: "",
        esgotado: false,
        preco: 40,
        foto: "Brinco de Prata 925 Ear Cuff 3 Corações.webp",
      },
      {
        id: 19,
        nome: "Brinco Zircônia Redonda",
        descricao: "Unissex 9mm",
        esgotado: false,
        preco: 50,
        foto: "Brinco de Prata 925 Zircônia Redonda Unissex 9mm.webp",
      },

      {
        nome: "Brinco cuff 4 Corações",
        descricao: "",
        esgotado: false,
        preco: 55,
        categoria: Categoria.Brincos,
        foto: "brinco-4-coracoes.jpeg",
      },
      {
        nome: "Brinco Círculos Detalhados",
        descricao: "",
        esgotado: false,
        preco: 55,
        categoria: Categoria.Brincos,
        foto: "brinco-argolas-iaguais.jpeg",
      },
      {
        nome: "Brinco Argolas Lisas",
        descricao: "",
        esgotado: false,
        preco: 40,
        categoria: Categoria.Brincos,
        foto: "brinco-argolas.jpeg",
      },
      {
        nome: "Brinco Círculo e Coração Detalhado",
        descricao: "",
        esgotado: false,
        preco: 50,
        categoria: Categoria.Brincos,
        foto: "brinco-coracao-argola.jpeg",
      },
      {
        nome: "Brinco Pedra",
        descricao: "unisex",
        esgotado: false,
        preco: 20,
        categoria: Categoria.Brincos,
        foto: "brinco-masc.jpeg",
      },
      {
        nome: "Brinco Borboletas e Ponto de Luz",
        descricao: "Trio",
        esgotado: false,
        preco: 55,
        categoria: Categoria.Brincos,
        foto: "brinco-trio-borboletas-pedrinha.jpeg",
      },
      {
        nome: "Brinco Corações Rosé",
        descricao: "Trio",
        esgotado: false,
        preco: 50,
        categoria: Categoria.Brincos,
        foto: "brinco-trio-coracao-rosa.jpeg",
      },
      {
        nome: "Brinco Corações Origami",
        descricao: "Trio",
        esgotado: false,
        preco: 55,
        categoria: Categoria.Brincos,
        foto: "brinco-trio-coracoes-origami.jpeg",
      },
      {
        nome: "Brinco Estrela,Coração e Ponto de Luz",
        descricao: "Trio",
        esgotado: false,
        preco: 50,
        categoria: Categoria.Brincos,
        foto: "brinco-trio-estrela-coracao-pedrinha.jpeg",
      },
    ],
  },
  {
    name: Categoria.Colares,
    foto: "DESTAQUE-COLAR.png",
    produtos: [
      {
        id: 10,
        nome: "Colar Rabo de Baleia Geométrico",
        descricao: "",
        esgotado: false,
        preco: 100,
        foto: "Colar de Prata 925 Rabo de Baleia Geométrico.webp",
      },
      {
        id: 11,
        nome: "Colar Trevo Detalhado Preto Pequeno",
        descricao: "",
        esgotado: false,
        preco: 90,
        foto: "Colar de Prata 925 Trevo Detalhado Preto Pequeno.webp",
      },
      {
        id: 12,
        nome: "Colar Veneziana com Bolinhas",
        descricao: "",
        esgotado: false,
        preco: 65,
        foto: "Colar de Prata 925 Veneziana com Bolinhas.webp",
      },
      {
        id: 13,
        nome: "Colar Mini Corações Vazados",
        descricao: "",
        esgotado: false,
        preco: 70,
        foto: "Colar de Prata 925 Mini Corações Vazados.webp",
      },
      {
        nome: "Colar Coração Cravaçao",
        descricao: "",
        esgotado: false,
        preco: 80,
        categoria: Categoria.Colares,
        foto: "colar-coracao-pedrinha pequena.jpeg",
      },
      {
        nome: "Colar Ponto de Luz",
        descricao: "",
        esgotado: false,
        preco: 65,
        categoria: Categoria.Colares,
        foto: "colar-ponto-luz.jpeg",
      },
    ],
  },
  {
    name: Categoria.Conjuntos,
    foto: "DESTAQUE-CONJUNTO.png",
    produtos: [
      {
        id: 1,
        nome: "Conjunto Coração Zircônia Preto",
        descricao: "Conjunto",
        esgotado: false,
        preco: 100,
        foto: "Conjunto De Prata 925 Coração Zircônia Preto.webp",
      },
      {
        id: 2,
        nome: "Conjunto Coração Vazado",
        descricao: "Conjunto",
        esgotado: false,
        preco: 100,
        foto: "Conjunto de Prata 925 Coração Vazado.webp",
      },
      {
        nome: "Conjunto Gota Azul",
        descricao: "Conjunto",
        esgotado: false,
        preco: 115,
        categoria: Categoria.Conjuntos,
        foto: "conjunto-azul.jpeg",
      },
      {
        nome: "Conjunto Gota Branca",
        descricao: "Conjunto",
        esgotado: false,
        preco: 115,
        categoria: Categoria.Conjuntos,
        foto: "conjunto-branco.jpeg",
      },
    ],
  },
  {
    name: Categoria.Pulseiras,
    foto: "DESTAQUE-PULSEIRA.png",
    produtos: [
      {
        id: 3,
        nome: "Pulseira Trevo Detalhado Rosa",
        descricao: "",
        esgotado: false,
        preco: 60,
        foto: "Pulseira de Prata 925 Trevo Detalhado Rosa.webp",
      },
      {
        id: 4,
        nome: "Pulseira Corações Rosas",
        descricao: "",
        esgotado: false,
        preco: 60,
        foto: "Pulseira de Prata 925 Corações Rosas.webp",
      },
      {
        nome: "Pulseira Corações Azuis",
        descricao: "",
        esgotado: false,
        preco: 55,
        categoria: Categoria.Pulseiras,
        foto: "pulseira-coracoes-azuis.jpeg",
      },
      {
        nome: "Pulseira Estrela e Coração",
        descricao: "",
        esgotado: false,
        preco: 65,
        categoria: Categoria.Pulseiras,
        foto: "pulseira-estrela-coracao.jpeg",
      },
      {
        nome: "Pulseira Pedrinhas Azuis",
        descricao: "",
        esgotado: false,
        preco: 65,
        categoria: Categoria.Pulseiras,
        foto: "pulseira-pedrinhas-azuis.jpeg",
      },
      {
        nome: "Pulseira Pedrinhas Douradas",
        descricao: "",
        esgotado: false,
        preco: 65,
        categoria: Categoria.Pulseiras,
        foto: "pulseira-pedrinhas-douradas.jpeg",
      },
      {
        nome: "Pulseira Pedrinhas Verdes",
        descricao: "",
        esgotado: false,
        preco: 65,
        categoria: Categoria.Pulseiras,
        foto: "pulseira-pedrinhas-verde.jpeg",
      },
      {
        nome: "Pulseira Trevo Vermelho",
        descricao: "",
        esgotado: false,
        preco: 70,
        categoria: Categoria.Pulseiras,
        foto: "pulseira-trevo-vermelho.jpeg",
      },
    ],
  },
  {
    name: Categoria.ColarMasc,
    foto: "colar-masc.png",
    produtos: [
      {
        id: 15,
        nome: "Colar Masculino Cruz com Detalhes",
        descricao: "",
        esgotado: false,
        preco: 110,
        foto: "Colar de Prata 925 Masculino Cruz com Detalhes.webp",
      },
      {
        nome: "Colar Masculino Cruz Geométrica",
        descricao: "",
        esgotado: false,
        preco: 110,
        categoria: Categoria.ColarMasc,
        foto: "colar-masc-cruz-geometrica.jpeg",
      },
      {
        nome: "Colar Cruz Detalhada",
        descricao: "",
        esgotado: false,
        preco: 100,
        categoria: Categoria.ColarMasc,
        foto: "colar-masc-cruz-preenchida.jpeg",
      },
      {
        nome: "Colar Cruz Vazada",
        descricao: "TAM Maior",
        esgotado: false,
        preco: 120,
        categoria: Categoria.ColarMasc,
        foto: "colar-masc-cruz-vazada-grande.jpeg",
      },
      {
        nome: "Colar Cruz Vazada",
        descricao: "TAM Menor",
        esgotado: false,
        preco: 100,
        categoria: Categoria.ColarMasc,
        foto: "colar-masc-cruz-vazada-pequena.jpeg",
      },
      {
        nome: "Colar Estrela de Davi",
        descricao: "",
        esgotado: false,
        preco: 110,
        categoria: Categoria.ColarMasc,
        foto: "colar-masc-estrela-davi.jpeg",
      },
    ],
  },
  {
    name: Categoria.PulseirasMasc,
    foto: "pulseira-masc.png",
    produtos: [
      {
        nome: "Pulseira Masculina Elos Piastrine",
        descricao: "",
        esgotado: false,
        preco: 90,
        foto: "Pulseira de Prata 925 Masculina Elos Piastrine.webp",
      },
      {
        nome: "Pulseira Elos Grumet Duplo",
        descricao: "3mm",
        esgotado: false,
        preco: 90,
        foto: "Pulseira de Prata 925 Elos Grumet Duplo 3mm.webp",
      },
      {
        nome: "Pulseira Masculina Elos 3x1",
        descricao: "4mm",
        esgotado: false,
        preco: 120,
        foto: "Pulseira Masculina de Prata 925 Elos 3x1 4mm.webp",
      },
      {
        nome: "Pulseira Masculina Elos Grumet",
        descricao: "4mm",
        esgotado: false,
        preco: 120,
        foto: "Pulseira Masculina de Prata 925 Elos Grumet 4mm.webp",
      },
      {
        nome: "Pulseira Masculina Elos 3x1",
        descricao: "5mm",
        esgotado: false,
        preco: 150,
        foto: "Pulseira Masculina de Prata 925 Elos 3x1 5mm.webp",
      },
      {
        nome: "Pulseira Masculina Elos Grumet",
        descricao: "5mm",
        esgotado: false,
        preco: 150,
        foto: "Pulseira Masculina de Prata 925 Elos Grumet 5mm.webp",
      },
      {
        nome: "Pulseira Masculina Lisa",
        descricao: "2mm",
        esgotado: false,
        preco: 90,
        categoria: Categoria.PulseirasMasc,
        foto: "pulseira-masc-chapa-2mm.jpeg",
      },
    ],
  },
];

// Mapeando os produtos para incluir a categoria
export const products: Produto[] = categories.flatMap((category) =>
  category.produtos.map((product) => ({
    ...product,
    categoria: category.name,
  }))
);
